name       : python-fonttools
version    : 4.32.0
release    : 2
source     :
    - https://github.com/fonttools/fonttools/archive/refs/tags/4.32.0.tar.gz : d3ac2454bb9b99dd0bd48f13765830d33dc2eabf3ba5232feb962620ebbde536
homepage   : https://github.com/fonttools/fonttools
license    : MIT
component  : programming.python
summary    : Tools to manipulate font files
description: |
    fontTools is a library for manipulating fonts, written in Python. The project includes the TTX tool, that can convert TrueType and OpenType fonts to and from an XML text format, which is also called TTX. It supports TrueType, OpenType, AFM and to an extent Type 1 and some Mac-specific formats.
builddeps  :
    - cython
build      : |
    %python3_setup
install    : |
    %python3_install
